profiles:  dev_environment
server:
  port: 9002
  servlet:
    context-path: /account
spring:
  datasource:
    url: @datasource.url@
    username: @datasource.username@
    password: @datasource.password@
    driver-class-name: org.postgresql.Driver
  application:
    name: data-server
  jpa:
    generate-ddl: true
    properties:
      format_sql: true
      hibernate:
        session_factory:
          statement_inspector: com.xiaowei.account.multi.SqlStatementInspector
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
  thymeleaf:
    cache: false
    cache-period: 0
  redis:
    host: @redis.url@
    port: 6379
    password: @redis.password@
  fluentd:
    host: @fluentd.url@
    port: @fluentd.port@
    label: @label@
  rabbitmq:
    host: @rabbitmq.host@
    port: @rabbitmq.port@
    username: @rabbitmq.username@
    password: @rabbitmq.password@
    publisher-confirms: true
    virtual-host: @rabbitmq.virtual.host@
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mail:
    host: smtp.163.com
    username: 13880298453@163.com
    password: 71H0BszikMolz7KE
    default-encoding: utf-8
logging:
  level:
    com:
      yulintu: DEBUG
upload:
  path: @upload.path@ #将此路径用iis配置发布
  type: local
  accessUrlRoot: @upload.accessUrlRoot@
  tags:
    - idCard #身份证
    - prove #证明
    - contract #合同
    - logo #头像
checkfield:
  names:
    - sys_company.logo
    - SYS_DEPARTMENT.logo
    - W_ENGINEERWORK.arrive_file_store
    - E_EXPENSEFORM.form_file_store
    - E_EXPENSEFORMITEM.invoice_file_store
    - E_EXPENSEFORMITEM.voucher_file_store
    - W_REQUESTWORKORDER.repair_file_store
    - W_REQUESTWORKORDER.repair_voice
    - W_SERVICEITEM.quality_file_store
    - W_WORKORDER.repair_file_store
    - W_WORKORDER.repair_voice
    - W_WORKFLOWNODE.standard_file_store
    - W_SERVICEITEM.standard_file_store
    - W_WORKFLOWITEM.standard_file_store
    - A_PUNCHRECORD.on_punch_file_store
    - A_PUNCHRECORD.off_punch_file_store

